### ISSUE TITLE
Not all rows loaded from user created file. (Originally: Not all stated relationships taken into account)

### ISSUE THREAD

**Issue by trudiger** [IHTSDO/snomed-owl-toolkit#27] opened 2019-07-14 11:27 UTC
Dear providers,

I am trying to classify a Snomed extension with the toolkit commandline.

(java -jar "C:\Users\thoma\Documents\PuffinPathology\Classifier\snomed-owl-toolkit-2.6.0-executable.jar" -classify -rf2-snapshot-archives "C:\Users\thoma\Documents\PuffinPathology\Classifier\SnomedCT_InternationalRF2_PRODUCTION_20190131T120000Z.zip" -rf2-authoring-delta-archive "C:\Users\thoma\Documents\PuffinPathology\Classifier\TR_Delta\SnomedCT_InternationalRF2_PRODUCTION_20190131T120000Z.zip")

The input is provided by the "-rf2-authoring-delta-archive " parameter. There are no other relevant files in the archive.
For a reason, that I cannot understand, the last of the stated attribute relationships does not appear in the inferred relationsships and appropriate is-A relationships from this last grouped attribute relationship are not inferred.
If I change the order of the attribute relationships, always the last one seems not to be taken into account.
What am I doing wrong?

5 rf2-files attached (3 input, 2 output)

Best regards
Thomas

[sct2_Concept_Delta_INT_20190131.txt](https://github.com/IHTSDO/snomed-owl-toolkit/files/3389768/sct2_Concept_Delta_INT_20190131.txt)
[sct2_StatedRelationship_Delta_INT_20190131.txt](https://github.com/IHTSDO/snomed-owl-toolkit/files/3389769/sct2_StatedRelationship_Delta_INT_20190131.txt)
[sct2_TextDefinition_Delta-en_INT_20190131.txt](https://github.com/IHTSDO/snomed-owl-toolkit/files/3389770/sct2_TextDefinition_Delta-en_INT_20190131.txt)

**Comment by trudiger** [comment] 2019-07-14 13:09
[classification-results-2019-07-14_13-59-54.zip](https://github.com/IHTSDO/snomed-owl-toolkit/files/3389892/classification-results-2019-07-14_13-59-54.zip)
[SnomedCT_InternationalRF2_PRODUCTION_20190131T120000Z.zip](https://github.com/IHTSDO/snomed-owl-toolkit/files/3389893/SnomedCT_InternationalRF2_PRODUCTION_20190131T120000Z.zip)

... attaching failed in the previous comment 
Here are the relavant zip-archives

**Comment by kaicode** [comment] 2019-07-15 10:57
Hi @trudiger,

Please make sure every line in your RF2 ends with a ends with a carriage return and line feed character.
The concept delta you attached does not have these characters at the end so it's quite possible that the last line will not be loaded. It's worth checking all the lines of the rest of your files too.
Let us know how it goes.

Kind regards, Kai

RF2 docs for reference: https://confluence.ihtsdotools.org/display/DOCRELFMT/3.1.1+General+Structure+of+Release+Files

**Comment by trudiger** [comment] 2019-07-15 11:26
Hi Kai,
Thank you very much. I will try and keep you informed.
Yours Thomas


Von meinem iPhone gesendet

Am 15.07.2019 um 12:57 schrieb Kai Kewley <notifications@github.com<mailto:notifications@github.com>>:


Hi @trudiger<https://github.com/trudiger>,

Please make sure every line in your RF2 ends with a ends with a carriage return and line feed character.
The concept delta you attached does not have these characters at the end so it's quite possible that the last line will not be loaded. It's worth checking all the lines of the rest of your files too.
Let us know how it goes.

Kind regards, Kai

RF2 docs for reference: https://confluence.ihtsdotools.org/display/DOCRELFMT/3.1.1+General+Structure+of+Release+Files

**Comment by kaicode** [comment] 2019-08-15 13:52
Closing this one for now. Please reopen if the issue is not yet resolved.

**Closed by kaicode** 2019-08-15 13:52 UTC
Labels: question

**Comment by trudiger** [comment] 2019-08-15 14:58
Dear Kai Kewley,

you were completely right!
Thank you very much for your help.
Thomas
________________________________
Von: Kai Kewley <notifications@github.com>
Gesendet: Donnerstag, 15. August 2019 15:52
An: IHTSDO/snomed-owl-toolkit <snomed-owl-toolkit@noreply.github.com>
Cc: Prof. Dr. med. Thomas Rüdiger <thomas.ruediger@iap-bonn.de>; Mention <mention@noreply.github.com>
Betreff: Re: [IHTSDO/snomed-owl-toolkit] Not all rows loaded from user created file. (Originally: Not all stated relationships taken into account) (#27)


Closed #27<https://github.com/IHTSDO/snomed-owl-toolkit/issues/27>.

**Comment by kaicode** [comment] 2019-08-15 16:13
Thanks for the good news Thomas 👍. I hope your data is behaving now 😄.
