### ISSUE TITLE
Include altLabels and synonyms in OWL

### ISSUE THREAD

**Issue by mmorine** [IHTSDO/snomed-owl-toolkit#23] opened 2019-02-06 21:36 UTC
Hi,
I'm trying to produce an OWL of SNOMED that includes all altLabels/synonyms, however when I run the .jar with:

`java -jar snomed-owl-toolkit-2.2.0-executable.jar -rf2-to-owl -rf2-snapshot-archives path/to/SnomedCT_InternationalRF2_PRODUCTION_20190131T120000Z.zip`

my resulting OWL file doesn't contain synonyms for any terms. For instance see the attached image of the term "Skin Graft Hematoma (Disorder)" in Protégé, whereas this term should have the synonyms shown [here](https://browser.ihtsdotools.org/?perspective=full&conceptId1=239182004&edition=us-edition&release=v20180901&server=https://prod-browser-exten.ihtsdotools.org/api/snomed/&langRefset=900000000000509007).

I'm guessing I'm using the executable improperly just not sure how.
Thanks in advance.

![image](https://user-images.githubusercontent.com/3054588/52375144-55a4ae80-2a35-11e9-8b8d-1b03f055819f.png)

**Comment by kaicode** [comment] 2019-02-07 08:17
Hi @mmorine, this toolkit is only currently capable of including the Fully Specified Name of concepts. Other options are being developed for including more english descriptions and translated content but these are in early stages.
Kind regards.

**Comment by kaicode** [comment] 2019-11-06 14:47
Closing as duplicate of #14 .

**Closed by kaicode** 2019-11-06 14:47 UTC
Labels: question
